apiVersion: apps/v1
kind: Deployment
metadata:
  name: risklens-frontend
  namespace: risklens
  labels:
    app: risklens-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: risklens-frontend
  template:
    metadata:
      labels:
        app: risklens-frontend
    spec:
      containers:
        - name: frontend
          image: REGION-docker.pkg.dev/risklens-frtb-2026/risklens/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

      terminationGracePeriodSeconds: 10
